name: Build and publish APPIMAGE package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
      build:
        description: 'Build number'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Build
      run: |
        VERSION=${{ github.event.inputs.version }}
        BUILD_NUMBER=${{ github.event.inputs.build }}
        export DESKTOPEDITORS_DEB_URL="https://s3.eu-west-1.amazonaws.com/repo-doc-onlyoffice-com/desktop/linux/debian/onlyoffice-desktopeditors_${VERSION}-${BUILD_NUMBER}_amd64.deb"

        make clean && make pkg2appimage all

        FILENAME=`ls out | grep .AppImage`

        echo $FILENAME > out/filename
        TARGETNAME=`sed "s|.AppImage|-$BUILD_NUMBER.AppImage|g" out/filename`
        
